### ISSUE TITLE
Adding newdata argument breaks code

### ISSUE THREAD

**Issue by tomhopper** [tomhopper/qcc_ggplot#6]
> my_data <- c(5054, 4350, 4350, 3975, 4290, 4430, 4485, 4285, 3980, 3925, 3645, 3760, 3300, 3685, 3463, 5200)
> qcc(my_data, type = "xbar.one", rules = shewhart.rules, newdata = my_data[1:6])
>  Hide Traceback

 Rerun with Debug
 Error: `breaks` and `labels` must have the same length 
7 stop("`breaks` and `labels` must have the same length", call. = FALSE) 
6 check_breaks_labels(breaks, labels) 
5 continuous_scale(c("x", "xmin", "xmax", "xend", "xintercept"), 
    "position_c", identity, name = name, breaks = breaks, minor_breaks = minor_breaks, 
    labels = labels, limits = limits, expand = expand, oob = oob, 
    na.value = na.value, trans = trans, guide = "none") 
4 scale_x_continuous(expand = c(0, 0.5), limits = xlim, breaks = df.indices, 
    labels = xlabs) at qcc.plot.R#185
3 plot.qcc(object, ...) 
2 plot(object, ...) 
1 qcc(my_data, type = "xbar.one", rules = shewhart.rules, newdata = my_data[1:6])

**Comment by OackMa** [comment]
If you until have this problem, I can fix it.
You can add following code at below #line 183 in qcc.plot.R.

`xlabs = as.character(v.indices)`

This script was missed applying new data label.

**Comment by tomhopper** [comment]
The underlying problem is that when adding new data, `v.indices` wasn't always being updated to add the new indices, so `breaks` included old data and new data, but `v.indices` sometimes only included the indices from the old data.

This is now fixed.
